### PR TITLE
Use ratation shifts for last bit swaps in reverse32/reverse64. Unhide build folder

### PR DESCRIPTION
**Pull request by MaxGraey**
Hi,
It's awesome that you chose AssemblyScript!

Let me suggest minor performance improvements.
You could replace `(x >> 16) | (x << 16)` and `(x >> 32) | (x << 32)` to cyclic rotation shifts which takes same cost as single shift operation.

Also I included build directory and add `.wat` files for observe output wasm quality.

I also recommend using unsigned types wherever possible. For example in future [such patterns like in current PR](https://github.com/WebAssembly/binaryen/pull/3079) will be match and optimize by compiler but only for unsigned shifts (types). This also applies to other optimizations. Working with unsigned numbers is much easier for the optimizer in any compiler.

Also you could try `-O3` flag. It usually faster `--optimize` (-O3s). But it's depend on how low level your code and what's you main benefits - size of code or speed.

That's again for interesting user case of AssembltScript!

### CODE REVIEW

**Comment by lexaknyazev** [comment]
Thanks for reaching out! I think we'll have couple more similar projects made with AssemblyScript in the near future.

> cyclic rotation shifts which takes same cost as single shift operation

Good catch!

> Also I included build directory and add `.wat` files for observe output wasm quality.

I omitted them initially to reduce git noise during early development, but it seems that bringing them back would improve UX for users and contributors.

> I also recommend using unsigned types wherever possible. 
> Working with unsigned numbers is much easier for the optimizer in any compiler.

This sounds interesting. My assumption was that since native wasm types are signed anyway, using unsigned semantics puts more burden on the compiler in general (besides specific optimizations).

> Also you could try `-O3` flag. It usually faster `--optimize` (-O3s). But it's depend on how low level your code and what's you main benefits - size of code or speed.

I'll evaluate the proposed updates on the dataset (not public yet) soon to get some speed and size numbers with regards to unsigned types and optimization flags.

**Comment by MaxGraey** [comment]
> This sounds interesting. My assumption was that since native wasm types are signed anyway, using unsigned semantics puts more burden on the compiler in general (besides specific optimizations).

Yes, WebAssembly have only `i32` and `i64` integer types, but unsigned nature reflects via operation suffixes on instructions level like `i32.shr_u` or `i32.div_u`. Optimized could much this instructions and simplify it. For example `(i32.div_u (i32.load $x) (i32.const 2))` could be simplified to `(i32.shr_u (i32.load $x) (i32.const 1))`. Or in term on language it's `x / 2` -> `x >>> 1` transformation. If `x` is `u32` or `u64` it's possible, but if `i32` or `i64` this optimization can't perform anymore due to signed division much more complicated. All compilers follow these rules.

**Comment by lexaknyazev** [comment]
Looking again into including build artifacts into version control. The dependency on the ASC compiler currently allows newer versions (e.g. `^0.14.9` allows `0.14.10`). This means that building a freshly checked out repo may result in different compiled files. We would strongly prefer to avoid such situation, so I think there are two options here:
- keep the `build/` folder hidden from git, OR
- use fixed ASC version in `package.json` and sync its updates with checked-in builds.

What's the established way of handling this? FWIW, `asinit` currently excludes only `.wasm` files but keeps `.wat` checked-in.

**Comment by lexaknyazev** [comment]
Thanks again for the improvement.

Here are some observations:
- Rotation replacement nicely reduced the code size as those functions are inlined many times.
- Changing all arithmetic right shifts (`>>`) to logical right shifts (`>>>`) had no visible effect on the generated code besides `shr_s` being replaced with `shr_u`. The compiled size and the performance remained the same. I'll look into the effects of changing variable types to `u32`/`u64` later.
- `-O3` slightly increases the size of modules with almost unnoticeable performance difference.

**Comment by MaxGraey** [comment]
> Changing all arithmetic right shifts (>>) to logical right shifts (>>>) had no visible effect on the generated code besides shr_s being replaced with shr_u. The compiled size and the performance remained the same. I'll look into the effects of changing variable types to u32/u64 later.

You could keep `>>` just change type to unsigned associated with RHS of expression (a >>> b and a >> b the same if `a` is `u32` for example)

**Pull request merged**
